### ISSUE TITLE
Example runs for the code

### ISSUE THREAD

**Issue by abhimaniyar** [amoradinejad/limHaloPT#10]
I installed the code following the instructions in the README file. In order to check if the code runs well, I did `./limHaloPT` as suggested in the README file. It seemed like the code was running, however, the run takes a while to complete. I realized that this was happening because of the `size_t ninterp = 150` parameter in the `main.c` file which gives number of points for redshift interpolation. In order to decrease the run time, I changed this parameter to `size_t ninterp = 5` and `nlines = 1` (just for 1 line) and ran the code. This is what I get:

```
$ ./limHaloPT
hm 131 0 0.000000e+00 1.971505e+02 1.604636e+06 1.536095e+02 -6.258736e+01 
hm 131 1 2.600000e+00 1.594386e+03 5.543890e+08 3.445934e+03 1.644612e+03 
hm 131 2 5.200000e+00 1.088735e+03 1.947773e+08 3.798287e+03 6.804291e+03 
hm 131 3 7.800000e+00 6.936088e+02 3.475170e+07 3.116919e+03 8.353733e+03 
hm 131 4 1.040000e+01 3.722656e+02 1.045218e+07 2.217445e+03 9.013637e+03 
for line 131 mom1, mom2, b1 and b2 interpolators initialized
Reference Cosmology initialized
Elapsed: 107.390372 seconds for ref cosmology
Segmentation fault: 11
```
No output file is produced. I am not sure if this is due to the change in `size_t ninterp` parameter. 
I think it would be great if a simpler sample run is provided to check the installation of the code which takes a reasonable time. Also, it would be good to mention what is the expected output of the sample run.

**Comment by amoradinejad** [comment]
I have previously addressed the request of the referee in giving more information about a simple sample run by adding comments in main.c file which includes example calls to useful functions of the package.  It seems I have not correctly responded to this thread here, although the changes were made to main.c file and in the comment of the commit I have made;  "To fix https://github.com/amoradinejad/limHaloPT/issues/10, several comments added to main.c and ps_line_hm.c, related to ninterp, output file paths. Output directory created." 

Please let me know if the requests are addressed.

**Comment by abhimaniyar** [comment]
According to the JOSS requirements (here: https://joss.readthedocs.io/en/latest/review_checklist.html <https://urldefense.proofpoint.com/v2/url?u=https-3A__joss.readthedocs.io_en_latest_review-5Fchecklist.html&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=j7NTX35lzotSaEysgWTW31rDj0okOldBCLczNlYAI8w&m=87YU7psLWOQYeS5uKAEh4WOPw7Hvp2FXY9wC5FBHIa8Jh6j1Di48E5mPw3j-IrC2&s=2MAZ1h2SyiVmgfe_s6uKyKad2ny3CLQuhg1aOBzH2v8&e=>), README should include examples and their details i.e. what is being run/what is the expected output/what are the things code can calculate and which functions to call for them etc. 

So I think it would be helpful to add these details in the README section.
