### ISSUE TITLE
Improve the order of #include files

### ISSUE THREAD

**Issue by ziotom78** [amoradinejad/limHaloPT#6]
Currently the code does not compile using GCC 11.1 because the structure `Cosmology` is used before being declared. This is due to the fact that in file `Include/header.h` the line

```c
#include "cosmology.h"  // In this file, the struct Cosmology is referenced many times…
```

comes **before** the line

```c
#include "global_structs.h" // …but the structure is defined here
```

One should change the order of the header files in `Include/header.h`, e.g.:

```c
#include "global_structs.h"
#include "cosmology.h"
#include "cubature.h"
#include "ir_res.h"
#include "line_ingredients.h"
#include "ps_halo_1loop.h"
#include "ps_line_hm.h"
#include "ps_line_pt.h"
#include "survey_specs.h"
#include "utilities.h"
#include "wnw_split.h"
```

**Comment by amoradinejad** [comment]
As suggested, the header files are reordered.
