### ISSUE TITLE
Issue with installation instructions

### ISSUE THREAD

**Issue by ziotom78** [amoradinejad/limHaloPT#8]
The installation instructions provided in the README and in the documentation do not work on my system.

Here are the instructions provided in the README:

> - To compile, type: make
> - To run, type: ./limHaloPT

Here is what happens:

```
$ cd limHaloPT
$ make
make: *** No targets specified and no makefile found.  Stop.
```

By looking in the archive, I found that the `makefile` is in folder `Source`. So, the correct way to compile it is using the command `make -C Source`, as `make` alone is not enough:

```
$ make -C Source
```

However, using the `-C` flag does not make the command provided in the README work:

```
$ ./limHaloPT
fish: Unknown command: ./limHaloPT
```

because the executable is in the `Source` directory. Fixing the path produces another error:

```
$ ./Source/limHaloPT
Unable to open file
```

which is unexpected, as the README did not mention the need to provide a «file». (Moreover, the program should print a more helpful message, as the user has absolutely no clue of the kind of file needed by the program).

I tried to move to the `Source` directory and run the program, but this time the effect was catastrophic:

```
$ cd Source
$ ./limHaloPT
fish: Job 1, './limHaloPT' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by amoradinejad** [comment]
To compile and run the code, one has to be in Source subdirectoryy. I have now edited the readme to correctly give the subdirectory from which the code has to be compiled and run to fix #8.

**Comment by ziotom78** [comment]
I just realized that your README points to the page at https://amoradinejad.github.io/limHaloPT/html/index.html:

> The full documentation of the code can be found on [Documentation](https://amoradinejad.github.io/limHaloPT/html/index.html).

However, the changes you did in commit cd7be5b0bf65ae0d1896062e50ae81a4c8b24d49 to fix the installation instructions did not affect the file `html/index.html`, which still contains the wrong instructions.

I would suggest to completely remove installation instructions from `html/index.html` to avoid duplication, or to synchronize them.

**Comment by amoradinejad** [comment]
The inconsistency between the two READMEs is now solved.
