### ISSUE TITLE
Linking Cuba and GSL libraries

### ISSUE THREAD

**Issue by abhimaniyar** [amoradinejad/limHaloPT#9]
To link the Cuba and GSL libraries to limHaloPT, instructions in the README file say: 

> make sure that the two libraries are correctly linked to limHaloPT by making necassary modifcations to the makefile (placed in Source directory) of limHaloPT package

I would suggest adding a line in the `makefile` where these modifications should be done. For someone who might not be familiar with such changes, this might be a tricky step.

**Comment by amoradinejad** [comment]
I added the following note to the makefile to indicate where the changes should be made to fix #9: 
"# NOTE: Depending on your installation paths for gsl and cuba libraries, you should add the links 
# for the INCLUDES and LIBS below, replacing -I/opt/local/include and  -L/opt/local/lib which are the 
# paths on the machine on which the code was developed. "
